//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int courtId { get; set; }
        public int bookingNumber { get; set; }
        public System.DateTime bookingDate { get; set; }
        public int bookingCode { get; set; }
        public int userId { get; set; }
        public System.DateTime date { get; set; }
        public int bookingRulesId { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual BookingRule BookingRule { get; set; }
        public virtual Court Court { get; set; }
    }
}
