//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Courts = new HashSet<Court>();
        }
    
        public int buildingId { get; set; }
        public string address { get; set; }
        public int organizationId { get; set; }
    
        public virtual ICollection<Court> Courts { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
