//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LadderRule
    {
        public LadderRule()
        {
            this.Ladders = new HashSet<Ladder>();
        }
    
        public int LadderRuleId { get; set; }
        public int challengeRange { get; set; }
        public bool challengeLower { get; set; }
        public int numLadders { get; set; }
    
        public virtual ICollection<Ladder> Ladders { get; set; }
    }
}
