//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Buildings = new HashSet<Building>();
        }
    
        public int organizationId { get; set; }
        public string orgName { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
    }
}
