//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Users = new HashSet<User>();
        }
    
        public string provinceId { get; set; }
        public string provinceName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
