//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserMatches = new HashSet<UserMatch>();
            this.UserLadders = new HashSet<UserLadder>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public int skillId { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> losses { get; set; }
        public Nullable<int> ties { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string streetAddress { get; set; }
        public string city { get; set; }
        public string provinceId { get; set; }
        public int countryId { get; set; }
        public string phoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string gender { get; set; }
        public string birthDate { get; set; }
        public int accountId { get; set; }
        public bool locked { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ICollection<UserMatch> UserMatches { get; set; }
        public virtual ICollection<UserLadder> UserLadders { get; set; }
    }
}
