//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMatch
    {
        public int userId { get; set; }
        public int gameId { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
